server:
  port: 8090
spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071"
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted   # allow shutdown endpoint to be accessed from any IP
  info:
    env:
      enabled: true   # enable env info endpoint
eureka:
  instance:
    prefer-ip-address: true     # prefer IP address over hostname in Eureka registry to avoid issues with Docker container names
  client:
    fetch-registry: true       # fetch registry from Eureka server to get service information of other services
    register-with-eureka: true  # register with Eureka server to be discovered by other services
    service-url:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "loans"
    description: "Eazy Bank loans application"
    version: "1.0.0"
    port: 8090
    developer: "yuosef jamal"