build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "yuosef jamal - Developer"
    email: "yuosef@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345


