


spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "yuosef jamal qa- Developer"
    email: "yuosefqa@eazybank.com"
  onCallSupport:
    - (555) 555-2222
    - (555) 523-2222

server:
  port: 9000